/* SPDX-FileCopyrightText: Copyright © 2026 PipeWireAO contributors */
/* SPDX-License-Identifier: MIT */

#ifndef PIPEWIREAO_PLUGINS_DISCARD_H
#define PIPEWIREAO_PLUGINS_DISCARD_H

#include <spa/param/props.h>

#define SPA_NAME_API_PIPEWIREAO_DISCARD "api.pipewireao.discard"
#define SPA_KEY_API_PIPEWIREAO_DISCARD_MINIMUM_BUFFER_SIZE \
	"api.pipewireao.discard.minimum-buffer-size"

/** Read-only counters exposed through SPA_PARAM_Props. */
enum spa_pipewireao_discard_prop {
	SPA_PROP_PIPEWIREAO_DISCARD_START = SPA_PROP_START_CUSTOM,
	SPA_PROP_PIPEWIREAO_DISCARD_BUFFERS = SPA_PROP_PIPEWIREAO_DISCARD_START,
	SPA_PROP_PIPEWIREAO_DISCARD_DATA_BLOCKS,
	SPA_PROP_PIPEWIREAO_DISCARD_BYTES,
	SPA_PROP_PIPEWIREAO_DISCARD_PROTOCOL_ERRORS,
	SPA_PROP_PIPEWIREAO_DISCARD_PROCESS_CALLS,
	SPA_PROP_PIPEWIREAO_DISCARD_PAYLOAD_DIGEST,
	SPA_PROP_PIPEWIREAO_DISCARD_DIGEST_BYTES,
};

#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_BUFFERS "discard.buffers"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_DATA_BLOCKS "discard.data-blocks"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_BYTES "discard.bytes"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_PROTOCOL_ERRORS \
	"discard.protocol-errors"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_PROCESS_CALLS "discard.process-calls"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_PAYLOAD_DIGEST \
	"discard.payload-digest"
#define SPA_PROP_INFO_PIPEWIREAO_DISCARD_DIGEST_BYTES "discard.digest-bytes"

#endif /* PIPEWIREAO_PLUGINS_DISCARD_H */
